(cl:in-package sensors-msg)
(cl:export '(AXCALIB-VAL
          AXCALIB
          AYCALIB-VAL
          AYCALIB
          AZCALIB-VAL
          AZCALIB
          AX-VAL
          AX
          AY-VAL
          AY
          AZ-VAL
          AZ
          AXRAW-VAL
          AXRAW
          AYRAW-VAL
          AYRAW
          AZRAW-VAL
          AZRAW
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          GX-VAL
          GX
          GY-VAL
          GY
          GZ-VAL
          GZ
          GXCALIB-VAL
          GXCALIB
          GYCALIB-VAL
          GYCALIB
          GZCALIB-VAL
          GZCALIB
          GXRAW-VAL
          GXRAW
          GYRAW-VAL
          GYRAW
          GZRAW-VAL
          GZRAW
          CURRTIME-VAL
          CURRTIME
))