// Generated by gencpp from file sensors/GPSData.msg
// DO NOT EDIT!


#ifndef SENSORS_MESSAGE_GPSDATA_H
#define SENSORS_MESSAGE_GPSDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <std_msgs/Float64.h>
#include <std_msgs/Float64.h>

namespace sensors
{
template <class ContainerAllocator>
struct GPSData_
{
  typedef GPSData_<ContainerAllocator> Type;

  GPSData_()
    : time()
    , lat()
    , long()  {
    }
  GPSData_(const ContainerAllocator& _alloc)
    : time(_alloc)
    , lat(_alloc)
    , long(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _time_type;
  _time_type time;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _lat_type;
  _lat_type lat;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _long_type;
  _long_type long;





  typedef boost::shared_ptr< ::sensors::GPSData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensors::GPSData_<ContainerAllocator> const> ConstPtr;

}; // struct GPSData_

typedef ::sensors::GPSData_<std::allocator<void> > GPSData;

typedef boost::shared_ptr< ::sensors::GPSData > GPSDataPtr;
typedef boost::shared_ptr< ::sensors::GPSData const> GPSDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensors::GPSData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensors::GPSData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensors::GPSData_<ContainerAllocator1> & lhs, const ::sensors::GPSData_<ContainerAllocator2> & rhs)
{
  return lhs.time == rhs.time &&
    lhs.lat == rhs.lat &&
    lhs.long == rhs.long;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensors::GPSData_<ContainerAllocator1> & lhs, const ::sensors::GPSData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensors

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sensors::GPSData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::GPSData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensors::GPSData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensors::GPSData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::GPSData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::GPSData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensors::GPSData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "127d8146da420293b29d277551a452ba";
  }

  static const char* value(const ::sensors::GPSData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x127d8146da420293ULL;
  static const uint64_t static_value2 = 0xb29d277551a452baULL;
};

template<class ContainerAllocator>
struct DataType< ::sensors::GPSData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensors/GPSData";
  }

  static const char* value(const ::sensors::GPSData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensors::GPSData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String time\n"
"std_msgs/Float64 lat\n"
"std_msgs/Float64 long\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::sensors::GPSData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensors::GPSData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time);
      stream.next(m.lat);
      stream.next(m.long);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPSData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensors::GPSData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensors::GPSData_<ContainerAllocator>& v)
  {
    s << indent << "time: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.time);
    s << indent << "lat: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.lat);
    s << indent << "long: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.long);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSORS_MESSAGE_GPSDATA_H
