set(_CATKIN_CURRENT_PACKAGE "cloud")
set(cloud_VERSION "0.0.0")
set(cloud_MAINTAINER "pi <pi@todo.todo>")
set(cloud_PACKAGE_FORMAT "2")
set(cloud_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(cloud_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(cloud_BUILDTOOL_DEPENDS "catkin")
set(cloud_BUILDTOOL_EXPORT_DEPENDS )
set(cloud_EXEC_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(cloud_RUN_DEPENDS "message_runtime" "roscpp" "rospy" "std_msgs")
set(cloud_TEST_DEPENDS )
set(cloud_DOC_DEPENDS )
set(cloud_URL_WEBSITE "")
set(cloud_URL_BUGTRACKER "")
set(cloud_URL_REPOSITORY "")
set(cloud_DEPRECATED "")