set(cloud_SETUP_PY_SETUP_MODULE "distutils.core")
set(cloud_SETUP_PY_VERSION "0.0.0")
set(cloud_SETUP_PY_SCRIPTS "")
set(cloud_SETUP_PY_PACKAGES "cloud")
set(cloud_SETUP_PY_PACKAGE_DIRS "scripts/cloud")
set(cloud_SETUP_PY_MODULES "")
set(cloud_SETUP_PY_MODULE_DIRS "")