# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from positioning/Position.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sensors.msg

class Position(genpy.Message):
  _md5sum = "6fb7f457c11907847ca6763dd0bb7aad"
  _type = "positioning/Position"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """sensors/GPSData gps
sensors/IMUData imu

================================================================================
MSG: sensors/GPSData
string time
float64 lat
float64 long

================================================================================
MSG: sensors/IMUData
float64 AxCalib
float64 AyCalib
float64 AzCalib
float64 Ax
float64 Ay
float64 Az
float64 AxRaw
float64 AyRaw
float64 AzRaw
float64 Vx
float64 Vy
float64 Vz
float64 Gx
float64 Gy
float64 Gz
float64 GxCalib
float64 GyCalib
float64 GzCalib
float64 GxRaw
float64 GyRaw
float64 GzRaw
float64 currTime
"""
  __slots__ = ['gps','imu']
  _slot_types = ['sensors/GPSData','sensors/IMUData']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       gps,imu

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Position, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.gps is None:
        self.gps = sensors.msg.GPSData()
      if self.imu is None:
        self.imu = sensors.msg.IMUData()
    else:
      self.gps = sensors.msg.GPSData()
      self.imu = sensors.msg.IMUData()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.gps.time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_24d().pack(_x.gps.lat, _x.gps.long, _x.imu.AxCalib, _x.imu.AyCalib, _x.imu.AzCalib, _x.imu.Ax, _x.imu.Ay, _x.imu.Az, _x.imu.AxRaw, _x.imu.AyRaw, _x.imu.AzRaw, _x.imu.Vx, _x.imu.Vy, _x.imu.Vz, _x.imu.Gx, _x.imu.Gy, _x.imu.Gz, _x.imu.GxCalib, _x.imu.GyCalib, _x.imu.GzCalib, _x.imu.GxRaw, _x.imu.GyRaw, _x.imu.GzRaw, _x.imu.currTime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.gps is None:
        self.gps = sensors.msg.GPSData()
      if self.imu is None:
        self.imu = sensors.msg.IMUData()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps.time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.gps.time = str[start:end]
      _x = self
      start = end
      end += 192
      (_x.gps.lat, _x.gps.long, _x.imu.AxCalib, _x.imu.AyCalib, _x.imu.AzCalib, _x.imu.Ax, _x.imu.Ay, _x.imu.Az, _x.imu.AxRaw, _x.imu.AyRaw, _x.imu.AzRaw, _x.imu.Vx, _x.imu.Vy, _x.imu.Vz, _x.imu.Gx, _x.imu.Gy, _x.imu.Gz, _x.imu.GxCalib, _x.imu.GyCalib, _x.imu.GzCalib, _x.imu.GxRaw, _x.imu.GyRaw, _x.imu.GzRaw, _x.imu.currTime,) = _get_struct_24d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.gps.time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_24d().pack(_x.gps.lat, _x.gps.long, _x.imu.AxCalib, _x.imu.AyCalib, _x.imu.AzCalib, _x.imu.Ax, _x.imu.Ay, _x.imu.Az, _x.imu.AxRaw, _x.imu.AyRaw, _x.imu.AzRaw, _x.imu.Vx, _x.imu.Vy, _x.imu.Vz, _x.imu.Gx, _x.imu.Gy, _x.imu.Gz, _x.imu.GxCalib, _x.imu.GyCalib, _x.imu.GzCalib, _x.imu.GxRaw, _x.imu.GyRaw, _x.imu.GzRaw, _x.imu.currTime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.gps is None:
        self.gps = sensors.msg.GPSData()
      if self.imu is None:
        self.imu = sensors.msg.IMUData()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gps.time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.gps.time = str[start:end]
      _x = self
      start = end
      end += 192
      (_x.gps.lat, _x.gps.long, _x.imu.AxCalib, _x.imu.AyCalib, _x.imu.AzCalib, _x.imu.Ax, _x.imu.Ay, _x.imu.Az, _x.imu.AxRaw, _x.imu.AyRaw, _x.imu.AzRaw, _x.imu.Vx, _x.imu.Vy, _x.imu.Vz, _x.imu.Gx, _x.imu.Gy, _x.imu.Gz, _x.imu.GxCalib, _x.imu.GyCalib, _x.imu.GzCalib, _x.imu.GxRaw, _x.imu.GyRaw, _x.imu.GzRaw, _x.imu.currTime,) = _get_struct_24d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_24d = None
def _get_struct_24d():
    global _struct_24d
    if _struct_24d is None:
        _struct_24d = struct.Struct("<24d")
    return _struct_24d
